all: 	greedy sa ga

greedy: greedy.cpp SumofGaussians.cpp
	g++ greedy.cpp SumofGaussians.cpp -o greedy

sa:		sa.cpp SumofGaussians.cpp
	g++ sa.cpp SumofGaussians.cpp -o sa

ga: 	ga.cpp SumofGaussians.cpp
	g++ ga.cpp SumofGaussians.cpp -o ga

clean:	
	rm greedy sa ga
